FROM oven/bun:1.2.2-alpine

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
COPY tsconfig.json ./

COPY bun.lock ./

RUN bun install
COPY . .
RUN bunx prisma generate
RUN bun run db:seed:admins
RUN bun run db:seed:animals



CMD ["bun", "index.ts"]